python main.py \
    --mode train \
    --train_json "data/vimmsd-train.json" \
    --train_image_folder "data/train-images" \
    --tokenizer "vinai/phobert-base-v2" \
    --text_encoder "vinai/phobert-base-v2" \
    --image_encoder "google/vit-base-patch16-224" \
    --batch_size 8 \
    --num_workers 4 \
    --fusion_method 'concat' \
    --num_epochs 15 \
    --patience 10 \
    --learning_rate 3e-5 \
    --val_size 0.1 \
    --random_state 42